from pe_reports.peExcept import SixGillAlertInsertException as ok

raise ok("test1","test2")
